# Generated by Django 5.0.4 on 2024-06-03 07:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default Title', max_length=200)),
                ('title_desck', models.CharField(default='Default Title Description', max_length=500)),
                ('photo', models.ImageField(default='default.jpg', upload_to='photos/')),
                ('top', models.BooleanField(default=False)),
                ('author', models.CharField(default='Default Author', max_length=100)),
                ('photo_autor', models.ImageField(default='default_author.jpg', upload_to='author_photos/')),
                ('name_object', models.CharField(default='Default Object Name', max_length=200)),
                ('kind_object', models.CharField(default='Default Kind Object', max_length=200)),
                ('name_cost', models.CharField(default='Default Cost Name', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', ckeditor.fields.RichTextField(default='Default description')),
            ],
        ),
    ]
